version: '3'

services:
  server:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    image: "venus/quantum"
    ports:
      - "8000:8000"
  client:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: "venus/theswitch"
    ports:
      - "3000:3000"
