version: '3'

services:
  backend:
#    restart: on-failure
    depends_on:
      - venus-mysql
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: "venus/beeple"
    ports:
      - "8080:8080"
  venus-mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABASE=venus
      - MYSQL_USER=venus
      - MYSQL_PASSWORD=venus
    ports:
      - 3306:3306
